<<<<<<< HEAD
# Generated by Django 3.1.6 on 2021-02-20 19:48
=======
# Generated by Django 3.1.6 on 2021-02-19 17:34
>>>>>>> 35c1829fbf9df4fdd6efa5b2bd6f0ab4c0099cff

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='job_applied',
        ),
    ]
