# Generated by Django 3.1.6 on 2021-02-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_candidate_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=models.IntegerField(max_length=10, null=True),
        ),
    ]
