# Generated by Django 3.1.6 on 2021-02-19 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_candidate_job_applied'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidate',
            name='job_applied',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, to='api.application'),
        ),
    ]
