# Generated by Django 3.1.6 on 2021-02-14 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20210214_1116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidate',
            name='mobile',
            field=models.IntegerField(null=True),
        ),
    ]
