# Generated by Django 3.1.6 on 2021-02-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20210219_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateIP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.GenericIPAddressField(db_index=True)),
            ],
        ),
    ]
