name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master

jobs:
  test:
    name: Run tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Build containers and run tests
      run:  docker-compose up -d

  deploy:
    name: Run deploy
    runs-on: ubuntu-latest
    on:
      push:
        branch:
          - master
        run: docker login --username={$USERNAME}_ --password={$PASSWORD} registry.heroku.com  & heroku container:push web & heroku container:release web
